import { GuildChannelManager, Permissions } from 'discord.js';

export const getLoggingChannel = async (
  guildChannelManager: GuildChannelManager,
  loggingChannel: string = process.env.LOGGING_CHANNEL
) => {
  const channel = guildChannelManager.cache.find(channel => {
    if (channel.type === 'GUILD_TEXT') {
      return channel.name.toLowerCase() === loggingChannel;
    }

    return false;
  });

  let textChannel = loggingChannel;

  if (channel?.isText()) return channel;
  else if (channel) textChannel += '-text';

  return guildChannelManager.create(textChannel, {
    type: 'GUILD_TEXT',
    topic: 'Logs generated by ' + guildChannelManager.client.user!.username,
    permissionOverwrites: [
      {
        type: 'role',
        id: guildChannelManager.guild?.roles.everyone,
        deny: Permissions.ALL
      }
    ]
  });
};
