import { GuildChannelManager, Permissions } from 'discord.js';

export const getLoggingChannel = async (
  guildChannelManager: GuildChannelManager,
  loggingChannel: string = process.env.LOGGING_CHANNEL
) => {
  if (!guildChannelManager) return;

  const channel = guildChannelManager.cache.find(channel => {
    if (channel.type === 'GUILD_TEXT') {
      return channel.name.toLowerCase() === loggingChannel;
    }

    return false;
  });

  if (channel) {
    if (channel.isText()) {
      return channel;
    }
  } else {
    return guildChannelManager.create(loggingChannel, {
      type: 'GUILD_TEXT',
      topic: 'Logs generated by ' + guildChannelManager.client.user!.username,
      permissionOverwrites: [
        {
          type: 'role',
          id: guildChannelManager.guild?.roles.everyone,
          deny: Permissions.ALL
        }
      ]
    });
  }
};
