import { GuildChannelManager, Permissions, TextChannel } from 'discord.js';

export const getLoggingChannel = async (
  guildChannelManager: GuildChannelManager,
  loggingChannel: string = process.env.LOGGING_CHANNEL
): Promise<TextChannel> => {
  const channel = guildChannelManager.cache.find(
    channel =>
      channel.type === 'GUILD_TEXT' &&
      channel.name.toLowerCase() === loggingChannel
  ) as TextChannel | undefined;

  if (channel) return channel;

  return guildChannelManager.create(loggingChannel, {
    type: 'GUILD_TEXT',
    topic:
      'Logs generated by ' +
      (guildChannelManager.client.user?.username || 'Unknown Bot'),
    permissionOverwrites: [
      {
        type: 'role',
        id: guildChannelManager.guild?.roles.everyone,
        deny: Permissions.ALL
      }
    ]
  });
};
